services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: coderank
      POSTGRES_USER: coderank
      POSTGRES_PASSWORD: coderank
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coderank -d coderank"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # keep your existing secret value
      CODERANK_JWT_SECRET: "UmFuZG9tU3VwZXJMb25nU2VjcmV0S2V5MTIzNDU2Nzg5MDEyMzQ1Njc4OTA="
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pgdata: